# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'MUKI_test_NDC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
  # Pods for HBuilder
    # 網路偵測
    pod 'ReachabilitySwift'
    # Firebase
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/Crashlytics'
    # GA/ODM	
    pod 'FirebaseAnalytics'
    # Line
    pod 'LineSDKSwift', '~> 5.0'
end


post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
            if target.name.start_with? "GoogleDataTransport"
                target.build_configurations.each do |config|
                  config.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'NO' 
                end
            end
        end
    end
end
